language: python
python:
- '3.6'
install:
- pip install -U pip wheel
- pip install tox
script:
- tox -epy36
- make sdist bdist
sudo: false
deploy:
  - provider: script
    script: bash dist_gemfury.sh
    skip_cleanup: true
    on:
      tags: true
cache:
  directories:
    - $HOME/.cache/pip
